### ISSUE TITLE
网站无法注册

### ISSUE THREAD

**Issue by jacktator** [luosijie/card#2]
第一个用户可以注册，第二个开始就无法注册了。
node后台有报错，
Unhandled promise rejection
E11000 duplicate key error inex: card.users.$collections_1 dup key: { : undefined}", "op" : 
xxxxxx

**Comment by luosijie** [comment]
谢谢，bug已经修复。
主要是因为 user文档 设置了一个没必要的 unique

**Comment by jacktator** [comment]
确认已解决！干得漂亮！
